"""AUTO: Added top_level key to venues

Revision ID: 14ea9a71acd5
Revises: a6f4cae697f6
Create Date: 2025-02-20 16:35:46.125442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ea9a71acd5'
down_revision: Union[str, None] = 'a6f4cae697f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('top_level_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key('venues_top_level_fkey', 'venues', 'top_level', ['top_level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venues_top_level_fkey', 'venues', type_='foreignkey')
    op.drop_column('venues', 'top_level_id')
    # ### end Alembic commands ###
