"""AUTO: Added job posting user

Revision ID: 4a84847be188
Revises: 62405c51a954
Create Date: 2025-03-06 19:19:04.661047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a84847be188'
down_revision: Union[str, None] = '62405c51a954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_jobs', sa.Column('user_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_jobs', 'user_id')
    # ### end Alembic commands ###
