"""AUTO: Added top-level tables

Revision ID: 7bbab3e7dd3f
Revises: 
Create Date: 2025-02-18 00:20:55.565881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbab3e7dd3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    top_level = op.create_table('top_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(top_level, [{'id': 1}])
    op.create_table('guild_ids',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_ids')
    op.drop_table('top_level')
    # ### end Alembic commands ###
