"""AUTO: added top level training_message_url

Revision ID: 9b621b6c381d
Revises: 4391d055b854
Create Date: 2025-03-13 16:27:52.566010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b621b6c381d'
down_revision: Union[str, None] = '4391d055b854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_level', sa.Column('trainee_message_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_level', 'trainee_message_url')
    # ### end Alembic commands ###
