"""AUTO: added perm jobs

Revision ID: 9d3d6a9ecd8f
Revises: 0562d02a655d
Create Date: 2025-03-11 17:32:59.320095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3d6a9ecd8f'
down_revision: Union[str, None] = '0562d02a655d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanent_jobs', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('permanent_jobs', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('permanent_jobs', sa.Column('description', sa.String(), nullable=False))
    op.add_column('permanent_jobs', sa.Column('position_id', sa.Integer(), nullable=False))
    op.add_column('permanent_jobs', sa.Column('post_url', sa.String(), nullable=True))
    op.add_column('permanent_jobs', sa.Column('salary', sa.String(), nullable=True))
    op.create_foreign_key('temporary_jobs_venues_fkey', 'permanent_jobs', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('temporary_jobs_venues_fkey', 'permanent_jobs', type_='foreignkey')
    op.drop_column('permanent_jobs', 'salary')
    op.drop_column('permanent_jobs', 'post_url')
    op.drop_column('permanent_jobs', 'position_id')
    op.drop_column('permanent_jobs', 'description')
    op.drop_column('permanent_jobs', 'user_id')
    op.drop_column('permanent_jobs', 'venue_id')
    # ### end Alembic commands ###
