"""Added candidate_id to Services

Revision ID: cd782fab3e42
Revises: e5944920521b
Create Date: 2025-07-20 19:29:16.801536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd782fab3e42'
down_revision: Union[str, None] = 'e5944920521b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('candidate_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'candidate_id')
    # ### end Alembic commands ###
