"""Added post_url to Services

Revision ID: e5944920521b
Revises: e92ffaa116a5
Create Date: 2025-07-20 18:55:50.261006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5944920521b'
down_revision: Union[str, None] = 'e92ffaa116a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('post_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'post_url')
    # ### end Alembic commands ###
