"""[AUTO:] Added candidate to perm jobs

Revision ID: e92ffaa116a5
Revises: 9f9386047272
Create Date: 2025-07-08 17:35:16.028053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92ffaa116a5'
down_revision: Union[str, None] = '9f9386047272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanent_jobs', sa.Column('candidate_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanent_jobs', 'candidate_id')
    # ### end Alembic commands ###
