"""Convert DJAvailability to range

Revision ID: f269cd2fcb96
Revises: cd782fab3e42
Create Date: 2025-08-28 17:31:42.277536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f269cd2fcb96'
down_revision: Union[str, None] = 'cd782fab3e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dj_profile_availability_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_min_local', sa.Integer(), nullable=False),
    sa.Column('end_min_local', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dj_profiles.user_id'], name='dj_profile_availability_dj_profiles_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dj_profile_availabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dj_profile_availabilities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['dj_profiles.user_id'], name='dj_profile_availability_dj_profiles_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dj_profile_availabilities_pkey')
    )
    op.drop_table('dj_profile_availability_ranges')
    # ### end Alembic commands ###
