"""AUTO: Added jobs tables

Revision ID: fb5d1497f952
Revises: 87dbf58d9f48
Create Date: 2025-03-06 06:55:51.255263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5d1497f952'
down_revision: Union[str, None] = '87dbf58d9f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permanent_jobs',
    sa.Column('top_level_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['top_level_id'], ['top_level.id'], name='permanent_jobs_top_level_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporary_jobs',
    sa.Column('top_level_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('start_dt', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_dt', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='temporary_jobs_positions_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['top_level_id'], ['top_level.id'], name='temporary_jobs_top_level_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='temporary_jobs_venues_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_jobs')
    op.drop_table('permanent_jobs')
    # ### end Alembic commands ###
