"""[AUTO:] Added new channels for channel mananger

Revision ID: 0da41ee245b2
Revises: 60d6f4d7c197
Create Date: 2025-07-03 16:28:29.898684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da41ee245b2'
down_revision: Union[str, None] = '60d6f4d7c197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_level', sa.Column('services_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('top_level', sa.Column('communication_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_level', 'communication_channel_id')
    op.drop_column('top_level', 'services_channel_id')
    # ### end Alembic commands ###
