"""AUTO: added dj post url and regions

Revision ID: 18e08f4782c0
Revises: 4195aaa1266c
Create Date: 2025-04-04 15:44:30.274272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e08f4782c0'
down_revision: Union[str, None] = '4195aaa1266c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dj_profiles', sa.Column('post_url', sa.String(), nullable=True))
    op.add_column('dj_profiles', sa.Column('regions', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dj_profiles', 'regions')
    op.drop_column('dj_profiles', 'post_url')
    # ### end Alembic commands ###
