"""AUTO: added venue special events

Revision ID: 311643665f19
Revises: b2becdc9da02
Create Date: 2025-04-13 16:05:19.796239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311643665f19'
down_revision: Union[str, None] = 'b2becdc9da02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('links', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='special_events_venues_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('top_level', sa.Column('special_event_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('venues', sa.Column('event_participation', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'event_participation')
    op.drop_column('top_level', 'special_event_channel_id')
    op.drop_table('special_events')
    # ### end Alembic commands ###
