"""AUTO: Added perm jobs channel

Revision ID: 380f58b6172e
Revises: fb5d1497f952
Create Date: 2025-03-06 09:02:04.167656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380f58b6172e'
down_revision: Union[str, None] = 'fb5d1497f952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_level', sa.Column('perm_jobs_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_level', 'perm_jobs_channel_id')
    # ### end Alembic commands ###
