"""AUTO: Added bg_check tables

Revision ID: 46512a99ba96
Revises: 14a8fa163e4d
Create Date: 2025-02-23 22:09:34.540922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46512a99ba96'
down_revision: Union[str, None] = '14a8fa163e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bg_checks',
    sa.Column('top_level_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('agree', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('names', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['top_level_id'], ['top_level.id'], name='bg_checks_top_level_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bg_check_venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bg_check_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_center', sa.Integer(), nullable=False),
    sa.Column('world', sa.Integer(), nullable=False),
    sa.Column('jobs', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['bg_check_id'], ['bg_checks.id'], name='bg_check_venues_bg_checks_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('top_level', sa.Column('bg_check_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_level', 'bg_check_channel_id')
    op.drop_table('bg_check_venues')
    op.drop_table('bg_checks')
    # ### end Alembic commands ###
