"""AUTO: added service requests

Revision ID: 60d6f4d7c197
Revises: 311643665f19
Create Date: 2025-04-24 17:03:07.004543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d6f4d7c197'
down_revision: Union[str, None] = '311643665f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('top_level_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('service', sa.Integer(), nullable=False),
    sa.Column('dc', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['top_level_id'], ['top_level.id'], name='temporary_jobs_top_level_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_requests')
    # ### end Alembic commands ###
