"""[AUTO:] Added message urls to service requests

Revision ID: 7bbfa5800d75
Revises: 0da41ee245b2
Create Date: 2025-07-03 16:55:20.236180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbfa5800d75'
down_revision: Union[str, None] = '0da41ee245b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_requests', sa.Column('message_urls', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('service_requests', sa.Column('accepted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_requests', 'accepted')
    op.drop_column('service_requests', 'message_urls')
    # ### end Alembic commands ###
