"""AUTO: Added profiles tables

Revision ID: 87dbf58d9f48
Revises: 46512a99ba96
Create Date: 2025-03-05 14:56:20.025913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dbf58d9f48'
down_revision: Union[str, None] = '46512a99ba96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_profiles',
    sa.Column('top_level_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('jobs', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('rates', sa.String(), nullable=True),
    sa.Column('position_ids', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('dm_pref', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('pronouns', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('clan', sa.String(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('mare', sa.String(), nullable=True),
    sa.Column('data_centers', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('likes', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('dislikes', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('main_image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['top_level_id'], ['top_level.id'], name='bg_checks_top_level_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('profile_additional_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['staff_profiles.user_id'], name='profile_additional_images_profile_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['staff_profiles.user_id'], name='profile_availability_profile_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('top_level', sa.Column('staff_role_id', sa.BigInteger(), nullable=True))
    op.add_column('top_level', sa.Column('staff_pending_role_id', sa.BigInteger(), nullable=True))
    op.add_column('top_level', sa.Column('venue_management_role_id', sa.BigInteger(), nullable=True))
    op.add_column('top_level', sa.Column('trainee_role_id', sa.BigInteger(), nullable=True))
    op.add_column('top_level', sa.Column('trainee_hiatus_role_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_level', 'trainee_hiatus_role_id')
    op.drop_column('top_level', 'trainee_role_id')
    op.drop_column('top_level', 'venue_management_role_id')
    op.drop_column('top_level', 'staff_pending_role_id')
    op.drop_column('top_level', 'staff_role_id')
    op.drop_table('profile_availabilities')
    op.drop_table('profile_additional_images')
    op.drop_table('staff_profiles')
    # ### end Alembic commands ###
