"""AUTO: Added logger config

Revision ID: a6f4cae697f6
Revises: fd99c4deb2a0
Create Date: 2025-02-20 12:51:32.663668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f4cae697f6'
down_revision: Union[str, None] = 'fd99c4deb2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_level', sa.Column('log_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('top_level', 'log_channel_id')
    # ### end Alembic commands ###
