"""AUTO: Added mute_venue_ids to dj profiles

Revision ID: b2becdc9da02
Revises: f23d0cdbabe8
Create Date: 2025-04-07 14:49:02.188386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2becdc9da02'
down_revision: Union[str, None] = 'f23d0cdbabe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dj_profiles', sa.Column('muted_venue_ids', sa.ARRAY(sa.BigInteger()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dj_profiles', 'muted_venue_ids')
    # ### end Alembic commands ###
