"""AUTO: added rp_level and venue_tags to profiles

Revision ID: ee6eac0df236
Revises: 9b621b6c381d
Create Date: 2025-03-13 19:11:21.176454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6eac0df236'
down_revision: Union[str, None] = '9b621b6c381d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_profiles', sa.Column('rp_level', sa.Integer(), nullable=True))
    op.add_column('staff_profiles', sa.Column('venue_tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_profiles', 'venue_tags')
    op.drop_column('staff_profiles', 'rp_level')
    # ### end Alembic commands ###
