"""AUTO: Added top-level tables

Revision ID: fd99c4deb2a0
Revises: 
Create Date: 2025-02-19 22:52:26.513665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd99c4deb2a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    top_level = op.create_table('top_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(top_level, [{'id': 1}])
    op.create_table('guild_ids',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xiv_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('mare_id', sa.String(), nullable=True),
    sa.Column('mare_password', sa.String(), nullable=True),
    sa.Column('hiring', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('nsfw', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('data_center', sa.Integer(), nullable=True),
    sa.Column('world', sa.Integer(), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('ward', sa.Integer(), nullable=True),
    sa.Column('plot', sa.Integer(), nullable=True),
    sa.Column('subdivision', sa.Boolean(), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('rp_level', sa.Integer(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('user_ids', sa.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.Column('position_ids', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('mute_ids', sa.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.Column('discord_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('app_url', sa.String(), nullable=True),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('end_minute', sa.Integer(), nullable=True),
    sa.Column('interval_type', sa.Integer(), nullable=True),
    sa.Column('interval_arg', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='venue_schedules_venues_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_schedules')
    op.drop_table('venues')
    op.drop_table('top_level')
    op.drop_table('guild_ids')
    # ### end Alembic commands ###
